### ISSUE TITLE
Evaluation on the entire candidate papers

### ISSUE THREAD

**Issue by 8X7K** [X3N4/neural_citation#2]
First of all, thank you so much for sharing these codes! I am very grateful to be able to reproduce the results of the experiment.

Just to clarify, I'd like to make a question.
In your paper, it seems like datasets are separated into training, validation and test, and that performance of recommendation is scored within each datasets.
But if I'd like to use the entire candidate papers on evaluation, I guess what I need to is modification in `evaluation.py` like this...

```diff
         if self.eval:
-            self.examples = data.test.examples
+            self.examples = data.train.examples + data.valid.examples + data.test.examples
             logger.info(f"Number of samples in BM25 corpus: {len(self.examples)}")
```

Am I right?

**Comment by timoklein** [comment]
Seems correct to me. I haven't looked into this code for a long time though until now.

**Comment by 8X7K** [comment]
OK. Thanks!
