### ISSUE TITLE
Key error when running the evaluator method

### ISSUE THREAD

**Issue by MaheshBabu11** [X3N4/neural_citation#4]
When generating the recommendation using NCN_presentation.ipynb file I am getting a key error. I am attaching the screenshot for the same
![key_error](https://user-images.githubusercontent.com/43287976/142130844-e7b620e2-ad41-4903-8d1e-4f10e7f94a18.png)
.

**Comment by timoklein** [comment]
I've tried to reproduce your error but the notebook code works for me. Did you change something?

**Comment by MaheshBabu11** [comment]
No, I have not. I have used the model that you have provided in the description and the same files.

**Comment by timoklein** [comment]
What environment are you using? Are the package version numbers exactly the same as specified in the environment?
I have updated it with the current env where I tried to reproduce your error.

**Comment by MaheshBabu11** [comment]
I did it in google colab with the same package versions.

**Comment by timoklein** [comment]
The last thing that I can think of is the Spacy language model version. If that's off, then the tokenization and removed stopwords are different.
You're using `en_core_web_lg-2.1.0`?
If that's not the case then I'm a little bit lost as it works for me locally on my laptop (Ubuntu 20.04) with the conda environment I uploaded earlier.

**Comment by MaheshBabu11** [comment]
I am using Spacy en_core_web_lg-2.1.0 . I think the error has something to do with the  .pkl files on which the keys are referenced. I am using the same files as in the asset folder.

**Comment by timoklein** [comment]
I understand. But then it's very odd that they're working for me.
The files are saved dictionaries that map a tokenized sequence (e.g. from the KeyError in your screenshot) to the un-tokenized sequence. An option would maybe be to generate them new with the `generate_dicts` notebook.
It's important that the preprocessing in the notebook matches the steps in the `data.py` file. But from looking at it quickly that seems fine.

Without being able to reproduce the error I can only give you hints at what's wrong.

**Comment by MaheshBabu11** [comment]
I can understand, i will run the generate_dicts notebook and get back to you in case any errors persist.

**Comment by MaheshBabu11** [comment]
![image](https://user-images.githubusercontent.com/43287976/142193715-d1494b1c-60e4-4598-97b5-0e0a125ac707.png)

I tried running it on my local machine. But now I am getting this error.
I am using the following version of packages.

torch=1.10.0
torchvision==0.3.0
torchtext==0.3.1
tensorboard==1.14.0
spacy==2.1.6
gensim==3.8.0
nltk==3.4.4
pandas==0.25.0
tqdm==4.32.2

**Comment by timoklein** [comment]
Have you tried executing the notebook cell twice? That fixed it for a research assistant at the chair.

**Comment by MaheshBabu11** [comment]
yes, I have run the cell many times. Stil getting the same error.

**Comment by timoklein** [comment]
I'm sorry, but I just ran the code from the notebook again and it works for me. 
It's hard for me to diagnose the problem further without being able to reproduce it.
![Screenshot from 2021-11-18 15-01-12](https://user-images.githubusercontent.com/36668911/142429645-cc99ecc3-fa9b-4a05-830a-f5f775b541e0.png)

**Comment by MaheshBabu11** [comment]
Is it possible in any way that you can share the virtual environment that you are using?. I think it may be because of the difference in packages.

**Comment by timoklein** [comment]
I'm using a conda environment. The updated specification is in the repo (the one I ran the code with today).

**Comment by MaheshBabu11** [comment]
Yes, once I have configured the environment similar to yours. I was able to replicate the results . I have tried using the same packages on windows but somehow the same error is popping up. However, I was successful in replicating the same results using Ubuntu 20.04 and anaconda.
Thank you for your help in resolving my queries.
